name: Create Randomized Fire Red
on: ["workflow_dispatch"]

jobs:
    create-randomized-fire-red:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'oracle'
            java-version: '21'
        - run: java -version
        - run: ls -la
        - run: echo ${{ vars.BASEPATH }}${{ vars.FIRERED }}