name: Create Randomized Fire Red
on: ["workflow_dispatch"]

jobs:
    create-randomized-fire-red:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'oracle'
            java-version: '21'
        - name: Get current date
          id: date
          run: echo "::set-output name=date::$(date +'%Y-%m-%d-%s.%N')"
        - run: mkdir -p ./original
        - run: wget -O ./original/rom.zip '${{ vars.BASEPATH }}${{ vars.FIRERED }}'
        - run: unzip ./original/rom.zip -d ./original
        - run: mv './original/Pokemon - FireRed Version (USA, Europe) (Rev 1).gba' ./original/rom.gba
        - run: mkdir -p ./randomized
        - run: java -jar ./universalpokemonrandomizer/PokeRandoZX.jar cli -i ./original/rom.gba -o ./randomized/randomized-red${{ steps.date.outputs.date }} -s ./universalpokemonrandomizer/test.rnqs
        - run: ls -la && ls -la ./randomized