name: Create Randomized Fire Red
on: ["workflow_dispatch"]

jobs:
    Explore-GitHub-Actions:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/setup-java@v4
          with:
            distribution: 'oracle'
            version: '21'
        - run: java -version