name: Create Randomized Gold
on: ["workflow_dispatch"]

jobs:
    create-randomized-gold:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'oracle'
            java-version: '21'
        - name: Get current date
          id: date
          run: echo "::set-output name=date::$(date +'%Y-%m-%d-%s.%N')"
        - run: mkdir -p ./original
        - run: wget -O ./original/rom.zip '${{ vars.BASEPATH }}${{ vars.GOLD }}'
        - run: unzip ./original/rom.zip -d ./original
        - run: mv './original/Pokemon - Gold Version (USA, Europe) (SGB Enhanced) (GB Compatible).gbc' ./original/rom.gbc
        - run: mkdir -p ./randomized/gold
        - name: Generate ROM name
          id: romname
          run: echo "::set-output name=romname::randomized-gold${{ steps.date.outputs.date }}"
        - run: java -jar ./universalpokemonrandomizer/PokeRandoZX.jar cli -i ./original/rom.gbc -o ./randomized/gold/${{ steps.romname.outputs.romname }} -s ./universalpokemonrandomizer/Original_Settings.rnqs
        - run: cd ./randomized/gold && zip ${{ steps.romname.outputs.romname }}.zip ${{ steps.romname.outputs.romname }}.gbc && rm -f ${{ steps.romname.outputs.romname }}.gbc
        - run: rm -rf ./original
        - name: Commit & Push changes
          uses: actions-js/push@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: 'main'