name: Create Randomized Fire Red
on: ["workflow_dispatch"]

jobs:
    create-randomized-fire-red:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'oracle'
            java-version: '21'
        - run: mkdir ./original
        - run: wget -O ./original/rom.zip '${{ vars.BASEPATH }}${{ vars.FIRERED }}'
        - run: ls -la
        - run: java -jar ./universalpokemonrandomizer/PokeRandoZX.jar cli -i ./original/rom.zip -o ./randomized-red -s ./universalpokemonrandomizer/test.rnqs
        - run: ls -la